SELECT * FROM Zones;
SELECT * FROM Threats WHERE zone_id = 1;
SELECT * FROM Reports WHERE threat_id = 3;
UPDATE Zones SET description = 'Updated description of Zone A' WHERE zone_id = 1;
UPDATE Threats SET threat_level = 'Critical' WHERE threat_id = 10;
DELETE FROM Reports WHERE report_id = 5;
DELETE FROM threats WHERE zone_id = 2 AND type = 'Natural Disaster';
SELECT * FROM Reports WHERE threat_id IN (SELECT threat_id FROM Threats WHERE threat_level = 'High');
SELECT zone_id, COUNT(*) AS threat_count FROM Threats GROUP BY zone_id;
SELECT threat_id, COUNT(*) AS report_count FROM Reports GROUP BY threat_id;
SELECT * FROM Reports WHERE report_date > '2025-02-01';
SELECT * FROM Threats WHERE threat_level = 'High';
UPDATE Reports SET report_date = '2025-03-10' WHERE report_id = 7;
SELECT Zones.name FROM Zones WHERE zone_id IN (SELECT zone_id FROM Threats WHERE type = 'Terrorism');
SELECT * FROM Reports WHERE description LIKE '%bombing%';
SELECT * FROM threats WHERE threat_level = 'High' AND zone_id = (SELECT zone_id FROM Zones WHERE name = 'Zone A');
SELECT DISTINCT Threats.* FROM Threats JOIN Reports ON Threats.threat_id = Reports.threat_id;
SELECT Reports.* FROM Reports JOIN Threats ON Reports.threat_id = Threats.threat_id WHERE Threats.threat_level = 'Medium';
SELECT AVG(report_count) FROM (SELECT COUNT(*) AS report_count FROM Reports GROUP BY threat_id) AS report_summary;
SELECT * FROM Reports WHERE description LIKE '%attack%';
